version: 0.0
os: linux
files:
  - source: /QA
    destination: /var/www/html/QA
  - source: /QA1
    destination: /var/www/html/QA1
  - source: /QA2
   destination: /var/www/html/QA3
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

